meta_product_name: "SoroSoro"
meta_title: "SoroSoro - Le sport, autrement"
meta_description: "Faire du sport, avec du matériel performant, tout en réduisant notre impact environnemental.
C'est notre engagement."
meta_image: "cover.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
